## Librerias

In [13]:
import pandas as pd

## DF

Tasa de suicidos

In [14]:
df_tasa = pd.read_csv("data\Tasa_suicidios\suicide-rate-who-mdb.csv")
df_tasa

,Entity,Code,Year,"Age-standardized death rate from self-inflicted injuries per 100,000 population - Sex: Both sexes - Age group: all ages"
0,Albania,ALB,1987,2.474300
1,Albania,ALB,1988,2.234553
2,Albania,ALB,1989,2.352273
3,Albania,ALB,1992,1.604659
4,Albania,ALB,1993,2.503264
...,...,...,...,...
4817,Venezuela,VEN,2012,2.629027
4818,Venezuela,VEN,2013,2.171715
4819,Venezuela,VEN,2014,1.994035
4820,Venezuela,VEN,2015,2.010758
4821,Venezuela,VEN,2016,2.942446

Numero de suicidos

In [15]:
df_num = pd.read_csv(r"data\num_suicidios_jovenes\suicide-rates-among-young-people-who-mdb.csv")
df_num

         Entity Code  Year  15–19 years  20–24 years  25–29 years
0       Albania  ALB  1987     2.899485     8.898015     2.432244
1       Albania  ALB  1988     1.578781     6.709158     1.702997
2       Albania  ALB  1989     1.557147     3.969567     5.038629
3       Albania  ALB  1992     3.073771     2.658564     1.927525
4       Albania  ALB  1993     4.595263     6.105006     4.125413
...         ...  ...   ...          ...          ...          ...
4782  Venezuela  VEN  2012     3.244654     3.576053     3.127036
4783  Venezuela  VEN  2013     2.208087     2.934232     2.949895
4784  Venezuela  VEN  2014     1.585020     2.380923     2.641347
4785  Venezuela  VEN  2015     1.892231     2.671919     2.048765
4786  Venezuela  VEN  2016     2.837793     3.699783     3.199509

[4787 rows x 6 columns]

Pobreza extrema

In [16]:
df_pobre = pd.read_csv("data\pobreza_extrema\share-of-population-in-extreme-poverty.csv")
df_f = df_pobre.dropna()
df_f

,Entity,Code,Year,Share of population in poverty ($3 a day),Population,World region according to OWID
832,Albania,ALB,1996,2.967841,3245680.0,Europe
838,Albania,ALB,2002,4.194722,3134095.0,Europe
841,Albania,ALB,2005,2.650218,3076156.0,Europe
844,Albania,ALB,2008,0.827308,2992933.0,Europe
848,Albania,ALB,2012,1.794590,2910003.0,Europe
...,...,...,...,...,...,...
59073,Zambia,ZMB,2015,67.892838,16399092.0,Africa
59080,Zambia,ZMB,2022,71.656150,20152935.0,Africa
59330,Zimbabwe,ZWE,2011,35.716999,13595421.0,Africa
59336,Zimbabwe,ZWE,2017,44.656873,14812484.0,Africa
59338,Zimbabwe,ZWE,2019,49.219894,15271377.0,Africa

Numero de psiquiatras

In [17]:
df_psquiatras = pd.read_csv("data\psiquiatras\psychiatrists-working-in-the-mental-health-sector.csv")
df_psquiatras

,Entity,Code,Year,"Total number of psychiatrists per 100,000 population"
0,Afghanistan,AFG,2019,0
1,Albania,ALB,2019,2
2,Algeria,DZA,2019,2
3,Andorra,AND,2019,10
4,Antigua and Barbuda,ATG,2019,1
...,...,...,...,...
138,Venezuela,VEN,2019,1
139,Vietnam,VNM,2019,1
140,Yemen,YEM,2019,0
141,Zambia,ZMB,2019,0
142,Zimbabwe,ZWE,2019,0

Num de suicidios por edades

In [18]:
df_j = pd.read_csv(r"data\num_suicidios_jovenes\suicide-rates-among-young-people-who-mdb.csv")
df_j

         Entity Code  Year  15–19 years  20–24 years  25–29 years
0       Albania  ALB  1987     2.899485     8.898015     2.432244
1       Albania  ALB  1988     1.578781     6.709158     1.702997
2       Albania  ALB  1989     1.557147     3.969567     5.038629
3       Albania  ALB  1992     3.073771     2.658564     1.927525
4       Albania  ALB  1993     4.595263     6.105006     4.125413
...         ...  ...   ...          ...          ...          ...
4782  Venezuela  VEN  2012     3.244654     3.576053     3.127036
4783  Venezuela  VEN  2013     2.208087     2.934232     2.949895
4784  Venezuela  VEN  2014     1.585020     2.380923     2.641347
4785  Venezuela  VEN  2015     1.892231     2.671919     2.048765
4786  Venezuela  VEN  2016     2.837793     3.699783     3.199509

[4787 rows x 6 columns]

Desempleo

In [19]:
df_des = pd.read_csv(r"data\Desempleo\unemployment-rate.csv")
df_des

           Entity Code  Year  Unemployment rate
0     Afghanistan  AFG  1991              7.972
1     Afghanistan  AFG  1992              7.958
2     Afghanistan  AFG  1993              7.908
3     Afghanistan  AFG  1994              7.883
4     Afghanistan  AFG  1995              7.868
...           ...  ...   ...                ...
6981     Zimbabwe  ZWE  2021              9.540
6982     Zimbabwe  ZWE  2022             10.087
6983     Zimbabwe  ZWE  2023              9.348
6984     Zimbabwe  ZWE  2024              9.435
6985     Zimbabwe  ZWE  2025              9.293

[6986 rows x 4 columns]

Alcoholismo

In [20]:
df_alco = pd.read_csv(r"data\Alcoholismo\total-alcohol-consumption-per-capita-litres-of-pure-alcohol.csv")
df_alco

           Entity Code  Year  Alcohol consumption
0     Afghanistan  AFG  2000                0.003
1     Afghanistan  AFG  2001                0.003
2     Afghanistan  AFG  2002                0.007
3     Afghanistan  AFG  2003                0.016
4     Afghanistan  AFG  2004                0.021
...           ...  ...   ...                  ...
4159     Zimbabwe  ZWE  2016                3.560
4160     Zimbabwe  ZWE  2017                3.520
4161     Zimbabwe  ZWE  2018                3.630
4162     Zimbabwe  ZWE  2019                3.630
4163     Zimbabwe  ZWE  2020                2.670

[4164 rows x 4 columns]